name: poseidon2
channels:
  - rapidsai
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - cudatoolkit=12.4
  - pdal
  - rioxarray
  - zarr
  - numpy
  - matplotlib
  - cmocean
  - jupyter
  - scipy
  - scikit-image
  - pandas
  - geopandas
  - cupy
  - gdal
  - laspy
  - opencv
  - tqdm
  - mpi4py
  - contextily
  - cxx-compiler
  - c-compiler
  - rasterio
  - pytest
  - pytest-cov
  - pytest-mock
  - cucim
  - svgpath2mpl
  - dask
  - pip:
      - pdal-plugins==1.6.2
