name: poseidon
channels:
  - defaults
dependencies:
  - python=3.12
  - pdal
  - rioxarray
  - zarr
  - numpy
  - matplotlib
  - cmocean
  - jupyter
  - scipy
  - scikit-image
  - pandas
  - geopandas
  - cupy
  - gdal
  - laspy
  - opencv
  - tqdm
  - mpi4py
  - contextily
  - cxx-compiler
  - c-compiler
  - rasterio
  - pytest
  - pytest-cov
  - pytest-mock
