name: poseidon
channels:
  - defaults
dependencies:
  - python=3.12
  - pdal
  - rioxarray
  - zarr
  - numpy
  - matplotlib
  - pandas
  - geopandas
  - jupyter
  - cupy
  - laspy
  - opencv
  - tqdm
  - scikit-image
  - cmocean
  - mpi4py
  - contextily
