name: poseidon
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _x86_64-microarch-level=3=2_broadwell
  - alsa-lib=1.2.14=hb9d3cd8_0
  - anyio=4.11.0=pyhcf101f3_0
  - aom=3.9.1=hac33072_0
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py311h49ec1c0_1
  - arrow=1.4.0=pyhcf101f3_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - attr=2.5.2=h39aace5_0
  - attrs=25.4.0=pyh71513ae_0
  - aws-c-auth=0.9.1=h48c9088_3
  - aws-c-cal=0.9.2=he7b75e1_1
  - aws-c-common=0.12.4=hb03c661_0
  - aws-c-compression=0.3.1=h92c474e_6
  - aws-c-event-stream=0.5.6=h82d11aa_3
  - aws-c-http=0.10.4=h94feff3_3
  - aws-c-io=0.22.0=h57f3b0d_1
  - aws-c-mqtt=0.13.3=h2b1cf8c_6
  - aws-c-s3=0.8.6=h4e5ac4b_5
  - aws-c-sdkutils=0.2.4=h92c474e_1
  - aws-checksums=0.2.7=h92c474e_2
  - aws-crt-cpp=0.34.3=h60c762c_1
  - aws-sdk-cpp=1.11.606=h2d2fbd4_3
  - azure-core-cpp=1.16.0=h3a458e0_1
  - azure-identity-cpp=1.12.0=ha729027_0
  - azure-storage-blobs-cpp=12.14.0=hb1c9500_1
  - azure-storage-common-cpp=12.10.0=h4bb41a7_3
  - azure-storage-files-datalake-cpp=12.12.0=h8b27e44_3
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.14.2=pyha770c72_0
  - bleach=6.2.0=pyh29332c3_4
  - blosc=1.21.6=he440d0b_1
  - branca=0.8.2=pyhd8ed1ab_0
  - brotli=1.1.0=hb03c661_4
  - brotli-bin=1.1.0=hb03c661_4
  - brotli-python=1.1.0=py311h1ddb823_4
  - brunsli=0.1=he3183e4_1
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hb9d3cd8_0
  - c-blosc2=2.21.3=h4cfbee9_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h3394656_0
  - capnproto=1.2.0=hfc315d8_0
  - ceres-solver=2.2.0=cpuhbc9e029_7
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=2.0.0=py311h5b438cf_0
  - charls=2.4.2=h59595ed_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - cmocean=4.0.3=pyhd8ed1ab_1
  - colorspacious=1.1.2=pyhecae5ae_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py311hdf67eae_2
  - cpd=0.5.5=h434a139_2
  - crc32c=2.8=py311haee01d2_0
  - cuda-cccl_linux-64=12.8.90=h06a4308_1
  - cuda-cudart-dev_linux-64=12.8.90=hd1a145a_0
  - cuda-cudart-static_linux-64=12.8.90=hd1a145a_0
  - cuda-cudart_linux-64=12.8.90=hd1a145a_0
  - cuda-nvrtc=12.8.93=hbdd6827_1
  - cuda-version=12.8=h30beaf8_3
  - cupy=13.6.0=py311h41781dc_0
  - cupy-core=13.6.0=py311h56f0b24_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dav1d=1.2.1=hd590300_0
  - dbus=1.16.2=h3c4dab8_0
  - debugpy=1.8.17=py311hc665b79_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - deprecated=1.2.18=pyhd8ed1ab_0
  - docutils=0.22.2=pyhd8ed1ab_0
  - donfig=0.8.1.post1=pyhd8ed1ab_1
  - double-conversion=3.3.1=h5888daf_0
  - draco=1.5.7=h00ab1b0_0
  - eigen=3.4.0=h171cf75_1
  - entrypoints=0.4=pyhd8ed1ab_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - fastrlock=0.8.3=py311h5eee18b_0
  - ffmpeg=8.0.0=gpl_h817a628_106
  - fgt=0.4.11=h87365c0_1
  - fmt=11.2.0=h07f6e7f_0
  - folium=0.20.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.60.1=py311h3778330_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freeglut=3.2.2=ha6d2627_3
  - freetype=2.14.1=ha770c72_0
  - freexl=2.0.0=h9dce30a_2
  - fribidi=1.0.16=hb03c661_0
  - gdk-pixbuf=2.44.4=h2b0a6b4_0
  - geopandas=1.1.1=pyhd8ed1ab_1
  - geopandas-base=1.1.1=pyha770c72_1
  - geos=3.14.0=h480dda7_0
  - geotiff=1.7.4=h1000f5c_4
  - gettext=0.25.1=h3f43e3d_1
  - gettext-tools=0.25.1=h3f43e3d_1
  - gflags=2.2.2=h5888daf_1005
  - giflib=5.2.2=hd590300_0
  - glog=0.7.1=hbabe93e_0
  - glslang=16.0.0=hfd11570_0
  - gmp=6.3.0=hac33072_2
  - graphite2=1.3.14=hecca717_2
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.1.0=h15599e2_0
  - hdf5=1.14.6=nompi_h6e4c0c1_103
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.11=pyhd8ed1ab_0
  - imagecodecs=2025.8.2=py311h5031496_4
  - imageio=2.37.0=pyhfb79c49_0
  - imath=3.2.2=hde8ca8f_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-gmmlib=22.8.2=hb700be7_0
  - intel-media-driver=25.3.4=hecca717_0
  - ipykernel=7.0.1=pyha191276_0
  - ipython=9.6.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.7=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jasper=4.2.8=he3c4edf_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - json-c=0.18=h6688a6e_0
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py311h38be061_2
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter=1.1.1=pyhd8ed1ab_1
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_console=6.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.9=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - jupyterlab_widgets=3.0.15=pyhd8ed1ab_0
  - jxrlib=1.1=hd590300_3
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py311h724c32c_1
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lark=1.3.0=pyhd8ed1ab_0
  - laspy=2.6.1=py311hf7b45f0_1
  - lazrs-python=0.8.0=py311h902ca64_1
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h0aef613_1
  - level-zero=1.25.0=hb700be7_0
  - libabseil=20250512.1=cxx17_hba17884_0
  - libaec=1.1.4=h3f801dc_0
  - libamd=3.3.3=haaf9dc3_7100102
  - libarchive=3.8.2=gpl_h7be2006_100
  - libarrow=20.0.0=hefc464c_23_cuda
  - libarrow-acero=20.0.0=hb826db4_23_cuda
  - libarrow-dataset=20.0.0=hb826db4_23_cuda
  - libasprintf=0.25.1=h3f43e3d_1
  - libasprintf-devel=0.25.1=h3f43e3d_1
  - libass=0.17.4=h96ad9f0_0
  - libavif16=1.3.0=h6395336_2
  - libblas=3.9.0=37_h4a7cf45_openblas
  - libbrotlicommon=1.1.0=hb03c661_4
  - libbrotlidec=1.1.0=hb03c661_4
  - libbrotlienc=1.1.0=hb03c661_4
  - libbtf=2.3.2=h32481e8_7100102
  - libcamd=3.3.3=h32481e8_7100102
  - libcap=2.76=h0b2e76d_0
  - libcblas=3.9.0=37_h0358290_openblas
  - libccolamd=3.3.4=h32481e8_7100102
  - libcholmod=5.3.1=h59ddab4_7100102
  - libclang-cpp21.1=21.1.3=default_h99862b1_0
  - libclang13=21.1.3=default_h746c552_0
  - libcolamd=3.3.4=h32481e8_7100102
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcublas=12.8.4.1=hbdd6827_1
  - libcufft=11.3.3.83=hbdd6827_1
  - libcups=2.3.3=hb8b1518_5
  - libcurand=10.3.9.90=hbdd6827_1
  - libcurl=8.16.0=h4e3cde8_0
  - libcusolver=11.7.3.90=hbdd6827_1
  - libcusparse=12.5.8.93=hbdd6827_1
  - libcxsparse=4.4.1=h32481e8_7100102
  - libdeflate=1.24=h86f0d12_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libflac=1.4.3=h59595ed_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgdal-arrow-parquet=3.11.4=h9945ef5_4
  - libgdal-core=3.11.4=habfead2_4
  - libgdal-hdf5=3.11.4=h966a9c2_4
  - libgdal-pg=3.11.4=h55c2262_4
  - libgdal-tiledb=3.11.4=h2465779_4
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgettextpo-devel=0.25.1=h3f43e3d_1
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran-ng=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.86.0=h1fed272_0
  - libglu=9.0.3=h5888daf_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=h767d61c_7
  - libgoogle-cloud=2.39.0=hdb79228_0
  - libgoogle-cloud-storage=2.39.0=hdbdcf42_0
  - libgpg-error=1.55=h3f2d84a_0
  - libgrpc=1.73.1=h3288cfb_1
  - libhwloc=2.12.1=default_h7f8ec31_1002
  - libhwy=1.3.0=h4c17acf_1
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - libjxl=0.11.1=h6cb5226_4
  - libklu=2.3.5=hf24d653_7100102
  - libkml=1.3.0=hf539b9f_1021
  - liblapack=3.9.0=37_h47877c9_openblas
  - liblapacke=3.9.0=37_h6ae95b6_openblas
  - libldl=3.3.2=h32481e8_7100102
  - libllvm21=21.1.4=hf7376ad_0
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libnvjitlink=12.8.93=hbdd6827_1
  - libogg=1.3.5=hd0c01bc_1
  - libopenblas=0.3.30=pthreads_h94d23a6_2
  - libopencv=4.12.0=qt6_py311h26a67da_607
  - libopengl=1.7.0=ha4b6fd6_2
  - libopentelemetry-cpp=1.21.0=hb9b0907_1
  - libopentelemetry-cpp-headers=1.21.0=ha770c72_1
  - libopenvino=2025.2.0=hb617929_1
  - libopenvino-auto-batch-plugin=2025.2.0=hed573e4_1
  - libopenvino-auto-plugin=2025.2.0=hed573e4_1
  - libopenvino-hetero-plugin=2025.2.0=hd41364c_1
  - libopenvino-intel-cpu-plugin=2025.2.0=hb617929_1
  - libopenvino-intel-gpu-plugin=2025.2.0=hb617929_1
  - libopenvino-intel-npu-plugin=2025.2.0=hb617929_1
  - libopenvino-ir-frontend=2025.2.0=hd41364c_1
  - libopenvino-onnx-frontend=2025.2.0=h1862bb8_1
  - libopenvino-paddle-frontend=2025.2.0=h1862bb8_1
  - libopenvino-pytorch-frontend=2025.2.0=hecca717_1
  - libopenvino-tensorflow-frontend=2025.2.0=h0767aad_1
  - libopenvino-tensorflow-lite-frontend=2025.2.0=hecca717_1
  - libopus=1.5.2=hd0c01bc_0
  - libparquet=20.0.0=h006c7c7_23_cuda
  - libparu=1.0.0=h17147ab_7100102
  - libpciaccess=0.18=hb9d3cd8_0
  - libpdal=2.9.2=h27656cb_3
  - libpdal-arrow=2.9.2=hafe1643_3
  - libpdal-core=2.9.2=he6d2dbf_3
  - libpdal-cpd=2.9.2=hbf27424_3
  - libpdal-draco=2.9.2=hbf27424_3
  - libpdal-e57=2.9.2=h5940b4d_3
  - libpdal-hdf=2.9.2=h57d577a_3
  - libpdal-icebridge=2.9.2=h57d577a_3
  - libpdal-nitf=2.9.2=ha76d7ce_3
  - libpdal-pgpointcloud=2.9.2=h2d8de6c_3
  - libpdal-tiledb=2.9.2=hdb2dcb6_3
  - libpdal-trajectory=2.9.2=hfe7ccb2_3
  - libpng=1.6.50=h421ea60_1
  - libpq=18.0=h3675c94_0
  - libprotobuf=6.31.1=h49aed37_2
  - librbio=4.3.4=h32481e8_7100102
  - libre2-11=2025.08.12=h7b12aa8_1
  - librsvg=2.60.0=h61e6d4b_0
  - librttopo=1.1.0=h96cd706_19
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.20=h4ab18f5_0
  - libspatialite=5.1.0=gpl_hcb59c51_118
  - libspex=3.2.3=had10066_7100102
  - libspqr=4.3.4=h852d39f_7100102
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libsuitesparseconfig=7.10.1=h92d6892_7100102
  - libsystemd0=257.9=h996ca69_0
  - libthrift=0.22.0=h454ac66_1
  - libtiff=4.7.1=h8261f1e_0
  - libudev1=257.9=h085a93f_0
  - libumfpack=6.3.5=heb53515_7100102
  - libunwind=1.8.3=h65a8314_0
  - liburing=2.12=hb700be7_0
  - libusb=1.0.29=h73b1eb8_0
  - libutf8proc=2.11.0=hb04c3b8_0
  - libuuid=2.41.2=he9a06e4_0
  - libva=2.22.0=h4f16b4b_2
  - libvorbis=1.3.7=h54a6638_2
  - libvpl=2.15.0=h54a6638_1
  - libvpx=1.14.1=hac33072_0
  - libvulkan-loader=1.4.328.1=h5279c79_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h9b100fa_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.12.2=hca5e8e5_0
  - libxml2=2.15.1=h26afc86_0
  - libxml2-16=2.15.1=ha9997c6_0
  - libxml2-devel=2.15.1=h26afc86_0
  - libxslt=1.1.43=h711ed8c_1
  - libzlib=1.3.1=hb25bd0a_0
  - libzopfli=1.0.3=h9c3ff4c_0
  - lxml=6.0.2=py311h8840267_1
  - lz4-c=1.10.0=h5888daf_1
  - lzo=2.10=h280c20c_1002
  - m2r2=0.3.4=pyhd8ed1ab_0
  - mapclassify=2.10.0=pyhd8ed1ab_1
  - markupsafe=3.0.3=py311h3778330_0
  - matplotlib-base=3.10.7=py311h0f3be63_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - metis=5.1.0=hd0bcaf9_1007
  - minizip=4.0.10=h05a5f5f_0
  - mistune=0.8.4=pyh1a96a4e_1006
  - mpfr=4.2.1=h90cbb55_3
  - mpg123=1.32.9=hc50e24c_0
  - mpi=1.0=openmpi
  - mpi4py=3.1.6=py311h4267d7f_0
  - msgpack-python=1.1.2=py311hdf67eae_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - muparser=2.3.5=h5888daf_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=6.5.3=pyhd8ed1ab_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.5=pyhe01879c_0
  - nitro=2.7.dev8=h59595ed_0
  - nlohmann_json=3.12.0=h54a6638_1
  - notebook=7.4.7=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numpy=2.3.3=py311h2e04523_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - opencv=4.12.0=qt6_py311hf44fbca_607
  - openexr=3.4.2=hff891e4_0
  - openh264=2.6.0=hc22cd8d_0
  - openjpeg=2.5.4=h55fea9a_0
  - openjph=0.24.1=h8d634f6_0
  - openldap=2.6.10=he970967_0
  - openmpi=4.1.6=hc5af2df_101
  - openssl=3.5.4=h26f9b46_0
  - orc=2.2.0=h1bc01a4_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py311hed34c8f_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.56.4=hadf4263_0
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.46=h1321c63_0
  - pdal=2.9.2=he64977a_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py311h98278a2_3
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h54a6638_1
  - platformdirs=4.5.0=pyhcf101f3_0
  - postgresql=18.0=hd2008fe_0
  - proj=9.7.0=hb72c0af_0
  - prometheus-cpp=1.3.0=ha5d0236_0
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - prompt_toolkit=3.0.52=hd8ed1ab_0
  - psutil=7.1.1=py311h49ec1c0_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pugixml=1.15=h3f63f65_0
  - pulseaudio-client=17.0=h9a8bead_2
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-opencv=4.12.0=qt6_py311h44848da_607
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyogrio=0.11.1=py311ha7e4d0d_1
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyproj=3.7.2=py311h4e6619b_2
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.14=hfe2f287_1_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-pdal=3.5.3=np2py311hd701fec_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.11=2_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - pywavelets=1.9.0=py311h0372a8f_1
  - pyyaml=6.0.3=py311h3778330_0
  - pyzmq=27.1.0=py311h2315fbb_0
  - qhull=2020.2=h434a139_5
  - qt6-main=6.9.3=h5c1c036_0
  - rav1e=0.7.1=h8fae777_3
  - re2=2025.08.12=h5301d42_1
  - readline=8.3=hc2a1206_0
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rpds-py=0.27.1=py311h902ca64_1
  - s2n=1.5.26=h5ac9029_0
  - scikit-image=0.25.2=py311hed34c8f_2
  - scikit-learn=1.7.2=py311hc3e1efb_0
  - scipy=1.16.2=py311h1e13796_0
  - sdl2=2.32.56=h54a6638_0
  - sdl3=3.2.24=h68140b3_0
  - send2trash=1.8.3=pyh0d859eb_1
  - setuptools=80.9.0=py311h06a4308_0
  - shaderc=2025.4=h3e344bc_0
  - shapely=2.1.2=py311hdb2cc66_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h03e3b7b_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - soupsieve=2.8=pyhd8ed1ab_0
  - spdlog=1.15.3=h6dc744f_1
  - spirv-tools=2025.4=hb700be7_0
  - sqlite=3.50.2=hb25bd0a_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - suitesparse=7.10.1=ha0f6916_7100102
  - svt-av1=3.1.2=hecca717_0
  - tbb=2022.2.0=hb60516a_1
  - terminado=0.18.1=pyh0d859eb_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tifffile=2025.10.16=pyhd8ed1ab_0
  - tiledb=2.28.1=h9da7523_2
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.15=h54e0aa7_0
  - tomli=2.3.0=pyhcf101f3_0
  - tornado=6.5.2=py311h49ec1c0_1
  - tqdm=4.67.1=py311h92b7b1e_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzcode=2025b=hb9d3cd8_0
  - tzdata=2025b=h04d1e81_0
  - unicodedata2=16.0.0=py311h49ec1c0_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - uriparser=0.9.8=hac33072_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wayland=1.24.0=h3e06ad9_0
  - wayland-protocols=1.45=hd8ed1ab_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - wheel=0.45.1=py311h06a4308_0
  - widgetsnbextension=4.0.14=pyhd8ed1ab_0
  - wrapt=1.17.3=py311h49ec1c0_1
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xerces-c=3.2.5=h988505b_2
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxscrnsaver=1.2.4=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xyzservices=2025.4.0=pyhd8ed1ab_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h280c20c_3
  - zarr=3.1.3=pyhcf101f3_0
  - zeromq=4.3.5=h387f397_9
  - zfp=1.0.1=h909a3a2_3
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb25bd0a_0
  - zlib-ng=2.2.5=hde8ca8f_0
  - zstandard=0.25.0=py311haee01d2_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - affine==2.4.0
      - click==8.3.0
      - click-plugins==1.1.1.2
      - cligj==0.7.2
      - contextily==1.6.2
      - geographiclib==2.1
      - geopy==2.4.1
      - mercantile==1.2.1
      - numcodecs==0.16.3
      - pdal-plugins==1.6.6
      - rasterio==1.4.3
      - rioxarray==0.19.0
      - xarray==2025.10.1
